Google Season of Docs organization applications
ExpressLRS/Docs pull request #189
Opened 2022-03-24 01:32 UTC by JyeSmith

https://developers.google.com/season-of-docs

2022-03-24 03:03 UTC, FOG-Yamato approved these changes

2022-03-24 03:10 UTC, StonedDawg requested changes
put it as a list here ( - ) to match the above list.

2022-03-24 03:14 UTC, StonedDawg reviewed
put it as a list (- ) here to match the above list

2022-03-24 03:19 UTC, StonedDawg approved these changes

2022-03-24 03:19 UTC, StonedDawg commented on docs/gsod.md
> +In-depth PID Tuning of RC vehicles (Multicopter, Fixed - Wing, Boat, Rover).
put a list prefix ( - ) here to match the above list

2022-03-24 21:48 UTC, merged

2022-04-18 06:58 UTC, tapaswenipathak commented
hi folks, how should someone contact you, if they are interested?