Added new hardware selection page
ExpressLRS/Docs pull request #297
Opened 2023-03-20 13:45 UTC by maybenikhil

Instead of focusing on detailing all hundred plus recievers and the tens of transmitters, condensed down to a guide of manufacturers and features to look out for. Feel free to comment if I missed anything, this is a long time in the making and I finally had the time to work on it.

2023-03-25 02:27 UTC, deadbytefpv requested changes
Thank you for your work on this page.

Apologies for the late review. I've made several comments on the new page. Please have a look and consider those changes.

Might want to also add redirects for those two pages that were removed and consolidated into this one page. I didn't see an edit for the redirect.yml page

2023-03-25 02:27 UTC, deadbytefpv commented on docs/hardware/hardware-selection.md
> +    Recievers with a PA/LNA will have a listed telemetry output power in dBm or mW
"Receivers"

2023-03-25 02:27 UTC, deadbytefpv commented on docs/hardware/hardware-selection.md
> +    PP Sized Recievers (absolute smallest, lowest range regardless of antennas):
"Receivers"

2023-03-25 02:27 UTC, deadbytefpv commented on docs/hardware/hardware-selection.md
> +This selection lists out some common features of transmitters and some examples of transmitters with those features
"This selection" or "This section"?

2023-03-25 02:27 UTC, deadbytefpv commented on docs/hardware/hardware-selection.md
> +    Certain manufacturers have made handsets with built in ELRS modules, which offer tigher integration with ELRS. These can be update through the handset as well as generally over WiFi as is standar
"tighter"

These can be "updated" through the handset...

2023-03-25 02:27 UTC, deadbytefpv commented on docs/hardware/hardware-selection.md
> +    Some handsets with built in ELRS include:
"built-in"

2023-03-25 02:27 UTC, deadbytefpv commented on docs/hardware/hardware-selection.md
> +    ExpressLRS offers both 2.4GHz and 900MHz systems, with each only working with receivers and transmitters of the same frequency. 2.4GHz is the currently most popular frequency given it's legality,
"feature set" or just "features"

"locked-in"

2023-03-25 02:27 UTC, deadbytefpv commented on docs/hardware/hardware-selection.md
> +    For new users unless you plan on flying hundreds of kilometers or in a high noise environment we reccomend 2.4GHz hardware:
Recommend is misspelled here

this section sounds like these are the ONLY ones we  recommend. Use "some of our recommendations" instead or any wording like that. ;)

2023-03-25 02:27 UTC, deadbytefpv commented on docs/hardware/hardware-selection.md
> +      * Radimoaster Ranger Nano
RadioMaster is misspelled here

2023-03-25 02:27 UTC, deadbytefpv commented on docs/hardware/hardware-selection.md
> +    Most ELRS Transmitters have a 250mW or 500mW power cap, but for that extra percentage of range, a select few 1W modules exist, packing that punch needed to go even further. These transmitters inc
This sounds like there's massive range difference between a 500mW and 1W tx modules. Doubling power doesn't always mean double the range/penetration.
consider rewording to "needed to go a bit further".

"temperature sensing to cool the rf components"

2023-03-25 02:27 UTC, deadbytefpv commented on docs/hardware/hardware-selection.md
> +      * RadioMaster Ranger
Ranger Micro and Ranger Nano are also 1W modules

2023-03-25 02:27 UTC, deadbytefpv commented on docs/hardware/hardware-selection.md
> +      * NamimnoRC Flash OLED
the older Namimno Flash non-OLED were 1W capable as well

2023-03-25 02:27 UTC, deadbytefpv commented on docs/hardware/hardware-selection.md
> +      * BetaFPV Micro TX
might want to include the Jumper Aion Nano module here.. Don't want anyone to feel left out.. :D

2023-03-25 02:27 UTC, deadbytefpv commented on docs/hardware/hardware-selection.md
> +    Most current transmitters with include a [backpack](../hardware/backpack/esp-backpack.md), which enables communication with accessories such as a VRX allowing for tighter integration with the tra
"will include"

"with a built-in... " (use a dash between built and in)

2023-03-30 07:59 UTC, maybenikhil commented on docs/hardware/hardware-selection.md
> +ExpressLRS is hashtag blessed with the benefit of there being many receivers available from a variety of manufacturers. This begs the question "Which receiver is best?" There is no best receiver, the
generalized with hardware or just removed the words

2023-03-30 08:02 UTC, maybenikhil commented on docs/hardware/hardware-selection.md
> +  * **Long Range:** For sure you need an LNA, an external antenna, and a PA to extend the telemetry range. This isn't to say these are required for long range, 5km is achievable on a ceramic antenna
fair, I think the best case for diversity is actually short/midrange freestyle but yk... propoganda (will correct)

2023-03-30 08:07 UTC, maybenikhil commented on docs/hardware/hardware-selection.md
> +    ExpressLRS offers both 2.4GHz and 900MHz systems, with each only working with receivers and transmitters of the same frequency. 2.4GHz is the currently most popular frequency given it's legality,
keeping locked in as two words

2023-03-30 08:40 UTC, deadbytefpv approved these changes

2023-03-30 08:48 UTC, deadbytefpv commented on docs/hardware/hardware-selection.md
> +      * Radimoaster Ranger Nano
You missed one.. :)

2023-03-30 09:03 UTC, deadbytefpv approved these changes
Sorry about this.. 

GH is saying there's still unresolved change request, but I looked and all's been resolved.

2023-03-30 13:21 UTC, merged