Add Terms and Conditions
ExpressLRS/Docs pull request #371
Opened 2024-02-20 22:57 UTC by maybenikhil

2024-02-21 05:07 UTC, deadbytefpv requested changes
I understand that the content came from a third-party service so there could be inaccuracies.

I would urge the others in the Dev team to do their review as well.
Even though not many do read these pages, we should ensure this is accurate for those who do.

2024-02-21 05:07 UTC, deadbytefpv commented on docs/info/terms-and-conditions.md
> +commercial purposes or for personal gain, without express advance written permission from us.
"without express advance written permission from us."
I don't think this applies, so might as well put in "without sufficient attribution to the source material."

2024-02-27 09:24 UTC, maybenikhil commented on docs/info/terms-and-conditions.md
> +
may as well keep it, highly unlikely but no issue with keeping it imo

2024-02-27 09:26 UTC, maybenikhil commented
i feel that saying "Service" not "the Service" lines up with legal speak and how Service is defined in the first section

2024-02-28 06:55 UTC, deadbytefpv approved these changes

2024-02-28 21:26 UTC, merged