Add RC Link Preset section
ExpressLRS/Docs pull request #405
Opened 2024-08-06 03:21 UTC by hyp0dermik-code

Addresses #379

2024-08-06 03:23 UTC, hyp0dermik-code commented
While I agree with @VitroidFPV that this is best for the Betaflight wiki, I think there would need to be some structure changes which might result in the link changing which is beyond the current scope.

As such I suspect it would be best to have it here for the moment, and perhaps look at moving it to the BF wiki when the structure has been tidied up a bit.

2024-08-06 03:24 UTC, hyp0dermik-code commented
Open for feedback on the concerns location in particular, along with any other suggestions

2024-08-06 03:37 UTC, deadbytefpv requested changes

2024-08-06 03:37 UTC, deadbytefpv commented on docs/quick-start/pre-1stflight.md
> +For flight controllers based on Betaflight, there are 'RC Link Presets' available that configure feedforward smoothing and associated link settings based on your packet rate and usage case. Using no
> can result in unwanted disturbances in feedforward

would be great if we can be a bit specific. e.g. "can result in jittery or noisy signal"

2024-08-06 03:40 UTC, deadbytefpv commented on docs/quick-start/pre-1stflight.md
> +For flight controllers based on Betaflight, there are 'RC Link Presets' available that configure feedforward smoothing and associated link settings based on your packet rate and usage case. Using no
you'll have to add a few words in the wordlist to appease the spellchecker or use different words altogether.

2024-08-06 09:14 UTC, deadbytefpv submitted a review, later dismissed

2024-08-13 21:08 UTC, maybenikhil commented
@hyp0dermik-code moved this to fc configuration (opinionated change) because I feel like it flows with the section better, and given the user has technically already read lua config in terms of the flow of the guide, they should know what frequency they wanted to use. Also changed some verbiage to be more accessible, particularly "next highest" felt unclear, especially to an audience that isn't always english fluent

2024-08-14 18:33 UTC, maybenikhil approved these changes

2024-08-14 18:33 UTC, merged